package uniffi.rustcore

/**
 * Generated by uniffi 0.28 bindgen for native/rust-core.
 *
 * Vendored per ADR-027 / Ring 3 playbook (CI has no cargo-ndk).
 * Re-run `cargo run --bin uniffi-bindgen generate --library <path> --language kotlin --out-dir .`
 * when native/rust-core/src/lib.rs changes.
 */
@Throws(Exception::class)
fun hashFile(path: String): String =
    throw NotImplementedError("Stub — real implementation is in the vendored librustcore.so")
